apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: seoul-traffic-model
  namespace: kubeflow-user-example-com
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    model:
      modelFormat:
        name: mlflow
      runtime: kserve-mlserver-custom
      storageUri: pvc://model-pvc/v1/
    containers:
      - name: kserve-container
        resources:
          requests:
            cpu: "200m"
            memory: "2Gi"
          limits:
            cpu: "500m"
            memory: "4Gi"