apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: seoul-traffic-model
  namespace: kubeflow-user-example-com
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    model:
      modelFormat:
        name: mlflow
      runtime: kserve-mlserver-custom
      storageUri: pvc://model-pvc/v1/
      imagePullPolicy: IfNotPresent   # 이 줄 추가
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"