apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: seoul-traffic-model
  namespace: kubeflow-user-example-com
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    containers:
      - name: seoul-traffic-mlserver
        image: seoul-traffic-mlserver:3.7.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"