apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: seoul-gbr-tune
spec:
  objective:
    type: minimize
    goal: 0.0
    objectiveMetricName: MAE

  metricCollectorSpec:
    collector:
      kind: StdOut

  parallelTrialCount: 2
  maxTrialCount: 10
  maxFailedTrialCount: 3

  algorithm:
    algorithmName: random

  parameters:
    - name: n_estimators
      parameterType: int
      feasibleSpace: { min: "50", max: "200" }
    - name: learning_rate
      parameterType: double
      feasibleSpace: { min: "0.01", max: "0.2" }
    - name: max_depth
      parameterType: int
      feasibleSpace: { min: "2", max: "10" }
    - name: subsample
      parameterType: double
      feasibleSpace: { min: "0.5", max: "1.0" }

  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: n_estimators
        reference: n_estimators
      - name: learning_rate
        reference: learning_rate
      - name: max_depth
        reference: max_depth
      - name: subsample
        reference: subsample

    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            restartPolicy: Never
            containers:
              - name: training-container
                image: seoul-katib-trial:latest
                imagePullPolicy: IfNotPresent
                command: ["python", "/app/tune.py"]
                args:
                  - "--n_estimators=${trialParameters.n_estimators}"
                  - "--learning_rate=${trialParameters.learning_rate}"
                  - "--max_depth=${trialParameters.max_depth}"
                  - "--subsample=${trialParameters.subsample}"
                  - "--start_date=2025-03-01"
                resources:
                  requests:
                    cpu: "500m"
                    memory: "1Gi"
                  limits:
                    cpu: "1"
                    memory: "2Gi"
                volumeMounts:
                  - name: dataset
                    mountPath: /dataset
            volumes:
              - name: dataset
                persistentVolumeClaim:
                  claimName: dataset-pvc

