apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seoul-traffic-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/S-KYUCHAN/seoul-traffic-mlops
    targetRevision: main
    path: gitops/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow-user-example-com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

